version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:508758754283:task-definition/aws-hello-world-host:1"
        LoadBalancerInfo:
          ContainerName: "rest-app"
          ContainerPort: "80"
        PlatformVersion: "LATEST"